/*
* generated by Xtext
*/
package at.ac.tuwien.big.me12.ui.contentassist;

import at.ac.tuwien.big.me12.ui.contentassist.AbstractGSMLDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GSMLDslProposalProvider extends AbstractGSMLDslProposalProvider {

}
