/*
 * generated by Xtext
 */
package at.ac.tuwien.big.me12.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.tuwien.big.me12.ui.internal.GSMLDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GSMLDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GSMLDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GSMLDslActivator.getInstance().getInjector(GSMLDslActivator.AT_AC_TUWIEN_BIG_ME12_GSMLDSL);
	}
	
}
