/**
 */
package csvml_metamodel.provider;

import csvml_metamodel.util.Csvml_metamodelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Csvml_metamodelItemProviderAdapterFactory extends Csvml_metamodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Csvml_metamodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link csvml_metamodel.FileDefinitionSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileDefinitionSetItemProvider fileDefinitionSetItemProvider;

	/**
	 * This creates an adapter for a {@link csvml_metamodel.FileDefinitionSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFileDefinitionSetAdapter() {
		if (fileDefinitionSetItemProvider == null) {
			fileDefinitionSetItemProvider = new FileDefinitionSetItemProvider(this);
		}

		return fileDefinitionSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link csvml_metamodel.FileDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileDefinitionItemProvider fileDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link csvml_metamodel.FileDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFileDefinitionAdapter() {
		if (fileDefinitionItemProvider == null) {
			fileDefinitionItemProvider = new FileDefinitionItemProvider(this);
		}

		return fileDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link csvml_metamodel.StaticField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StaticFieldItemProvider staticFieldItemProvider;

	/**
	 * This creates an adapter for a {@link csvml_metamodel.StaticField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStaticFieldAdapter() {
		if (staticFieldItemProvider == null) {
			staticFieldItemProvider = new StaticFieldItemProvider(this);
		}

		return staticFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link csvml_metamodel.AggregationField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AggregationFieldItemProvider aggregationFieldItemProvider;

	/**
	 * This creates an adapter for a {@link csvml_metamodel.AggregationField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAggregationFieldAdapter() {
		if (aggregationFieldItemProvider == null) {
			aggregationFieldItemProvider = new AggregationFieldItemProvider(this);
		}

		return aggregationFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link csvml_metamodel.RuleBasedField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RuleBasedFieldItemProvider ruleBasedFieldItemProvider;

	/**
	 * This creates an adapter for a {@link csvml_metamodel.RuleBasedField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRuleBasedFieldAdapter() {
		if (ruleBasedFieldItemProvider == null) {
			ruleBasedFieldItemProvider = new RuleBasedFieldItemProvider(this);
		}

		return ruleBasedFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link csvml_metamodel.ComparisonRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComparisonRuleItemProvider comparisonRuleItemProvider;

	/**
	 * This creates an adapter for a {@link csvml_metamodel.ComparisonRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComparisonRuleAdapter() {
		if (comparisonRuleItemProvider == null) {
			comparisonRuleItemProvider = new ComparisonRuleItemProvider(this);
		}

		return comparisonRuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link csvml_metamodel.CompositeRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeRuleItemProvider compositeRuleItemProvider;

	/**
	 * This creates an adapter for a {@link csvml_metamodel.CompositeRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeRuleAdapter() {
		if (compositeRuleItemProvider == null) {
			compositeRuleItemProvider = new CompositeRuleItemProvider(this);
		}

		return compositeRuleItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (fileDefinitionSetItemProvider != null) fileDefinitionSetItemProvider.dispose();
		if (fileDefinitionItemProvider != null) fileDefinitionItemProvider.dispose();
		if (staticFieldItemProvider != null) staticFieldItemProvider.dispose();
		if (aggregationFieldItemProvider != null) aggregationFieldItemProvider.dispose();
		if (ruleBasedFieldItemProvider != null) ruleBasedFieldItemProvider.dispose();
		if (comparisonRuleItemProvider != null) comparisonRuleItemProvider.dispose();
		if (compositeRuleItemProvider != null) compositeRuleItemProvider.dispose();
	}

}
