/*
 * generated by Xtext
 */
package at.ac.tuwien.big.me12;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GSMLDslRuntimeModule extends at.ac.tuwien.big.me12.AbstractGSMLDslRuntimeModule {

}
