<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test3" nsURI="http://test3/1.0" nsPrefix="test3">
  <eClassifiers xsi:type="ecore:EClass" name="Artikel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minPreis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPreis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ersatzartikel" eType="#//Artikel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="warengruppe" lowerBound="1"
        eType="#//Warengruppe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieferanten" upperBound="-1"
        eType="#//Lieferantengruppe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Warengruppe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bez" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lieferantengruppe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="istGrossLieferant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieferant" lowerBound="1"
        upperBound="-1" eType="#//Lieferant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lieferant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
