/*
 * generated by Xtext
 */
package at.ac.tuwien.big.me12.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GSMLDslUiModule extends at.ac.tuwien.big.me12.ui.AbstractGSMLDslUiModule {
	public GSMLDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
